# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fe431ee1077d0cd6946bca03fd67964"
name = "PayAfrika"
application_url = "https://payafrika.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "payafrika-dev.myshopify.com"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://payafrika.fly.dev/auth/callback",
  "https://payafrika.fly.dev/auth/shopify/callback",
  "https://payafrika.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://payafrika.fly.dev/proxy"
subpath = "payafrika"
prefix = "apps"

[pos]
embedded = false
